# Generated by Django 5.2.6 on 2025-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
